# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pto',
                'doc_host': 'https://BavarianToolbox.github.io',
                'git_url': 'https://github.com/BavarianToolbox/pto',
                'lib_path': 'pto'},
  'syms': {'pto.core': {'pto.core.foo': ('core.html#foo', 'pto/core.py')}}}
